# /etc/security/limits.d/99-robotics.conf
# Allow all users to use RT scheduling and lock memory

*    soft  rtprio     99
*    hard  rtprio     99
*    soft  memlock    unlimited
*    hard  memlock    unlimited
*    soft  nofile     65536
*    hard  nofile     65536
root soft  rtprio     99
root hard  rtprio     99
root soft  memlock    unlimited
root hard  memlock    unlimited
