do_configure:append() {
    # GCC 15 made openat2's open_how pointer const in system headers.
    # pseudo_wrapfuncs.c is generated by configure, so patch it here.
    python3 -c "
import sys
path = '${S}/pseudo_wrapfuncs.c'
try:
    txt = open(path).read()
except FileNotFoundError:
    print('pseudo_wrapfuncs.c not found, skipping patch')
    sys.exit(0)
orig = txt
txt = txt.replace('struct open_how *how', 'const struct open_how *how')
if txt != orig:
    open(path, 'w').write(txt)
    print('pseudo openat2 const patch applied')
else:
    print('pseudo openat2: nothing to patch (already const or not present)')
"
}
